# Generated by Django 5.2.14 on 2026-06-23 12:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DividendPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('DIVIDEND', 'Dividend'), ('COUPON', 'Coupon')], default='DIVIDEND', max_length=8)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('tax_withheld', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(choices=[('RUB', 'Russian Ruble'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('CNY', 'Chinese Yuan')], default='USD', max_length=3)),
                ('paid_on', models.DateField()),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dividends', to='portfolio.asset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['-paid_on', '-id'],
                'indexes': [models.Index(fields=['portfolio', '-paid_on'], name='portfolio_d_portfol_769234_idx')],
            },
        ),
    ]
