# Generated by Django 5.2.14 on 2026-06-23 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_dividendpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateField()),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('invested', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(choices=[('RUB', 'Russian Ruble'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('CNY', 'Chinese Yuan')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['as_of'],
                'indexes': [models.Index(fields=['portfolio', 'as_of'], name='portfolio_p_portfol_f3c01c_idx')],
                'constraints': [models.UniqueConstraint(fields=('portfolio', 'as_of'), name='uniq_snapshot_portfolio_asof')],
            },
        ),
    ]
