# Generated by Django 5.2.14 on 2026-06-24 12:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfoliosnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='BondDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_value', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('coupon_rate', models.DecimalField(decimal_places=4, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('coupon_frequency', models.PositiveSmallIntegerField(choices=[(1, 'Annual'), (2, 'Semi-annual'), (4, 'Quarterly'), (12, 'Monthly')], default=2)),
                ('maturity_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bond', to='portfolio.asset')),
            ],
        ),
    ]
