# Generated by Django 5.2.14 on 2026-06-24 13:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_bonddetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='RebalanceTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_weight', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rebalance_targets', to='portfolio.asset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rebalance_targets', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['-target_weight'],
                'constraints': [models.UniqueConstraint(fields=('portfolio', 'asset'), name='uniq_target_portfolio_asset')],
            },
        ),
    ]
