# Generated by Django 5.2.14 on 2026-06-24 13:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_rebalancetarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('SPLIT', 'Stock split')], default='SPLIT', max_length=8)),
                ('effective_date', models.DateField()),
                ('new_shares', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('old_shares', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_actions', to='portfolio.asset')),
            ],
            options={
                'ordering': ['-effective_date', '-id'],
                'indexes': [models.Index(fields=['asset', 'effective_date'], name='portfolio_c_asset_i_ac7249_idx')],
                'constraints': [models.UniqueConstraint(fields=('asset', 'effective_date', 'kind'), name='uniq_corpaction_asset_date_kind')],
            },
        ),
    ]
