# Generated by Django 5.2.14 on 2026-06-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_corporateaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='share_token',
            field=models.CharField(blank=True, default=None, max_length=43, null=True, unique=True),
        ),
    ]
