# Generated by Django 5.2.14 on 2026-06-03 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('currency', models.CharField(max_length=3)),
                ('as_of', models.DateTimeField()),
                ('source', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='portfolio.asset')),
            ],
            options={
                'ordering': ['-as_of'],
                'indexes': [models.Index(fields=['asset', '-as_of'], name='marketdata__asset_i_253ef1_idx')],
                'constraints': [models.UniqueConstraint(fields=('asset', 'as_of', 'source'), name='uniq_quote_asset_asof_source')],
            },
        ),
    ]
