# Generated by Django 5.2.14 on 2026-06-25 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0002_pricealert'),
        ('portfolio', '0007_portfolio_is_public_portfolio_share_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('currency', models.CharField(max_length=3)),
                ('source', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividend_records', to='portfolio.asset')),
            ],
            options={
                'ordering': ['-ex_date'],
                'indexes': [models.Index(fields=['asset', '-ex_date'], name='marketdata__asset_i_0c4b5f_idx')],
                'constraints': [models.UniqueConstraint(fields=('asset', 'ex_date', 'source'), name='uniq_dividend_asset_exdate_source')],
            },
        ),
    ]
